Feature/ichiban
tf00185077/ichiban pull request #6
Opened 2024-05-16 05:48 UTC by ryanhsuyo

2024-05-16 05:51 UTC, tf00185077 requested changes

2024-05-16 05:51 UTC, tf00185077 commented on src/App.tsx
> -      <Header></Header>
strictmode放在main.jsx
outlet外層用maincard

2024-05-16 05:51 UTC, tf00185077 commented on src/pages/ichiban/SelectListsComponents/Card.tsx
> +// Card.tsx
component不要放在Page資料夾
之後找component可能找錯位置

2024-05-16 05:51 UTC, tf00185077 commented on src/pages/ichiban/SelectBarComponents/SelectBarComponents/SearchBar.tsx
> -
component不要放page資料夾
會找錯位置

2024-05-17 14:02 UTC, ryanhsuyo commented
@tf00185077 PTAL

2024-05-17 15:45 UTC, merged